services:

  node1:
    build:
      context: .
      dockerfile: Containerfile
    image: localhost/otel-poc:latest
    pull_policy: build
    container_name: node1
    hostname: node1
    privileged: true
    cgroup: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    networks:
      otel-poc-net:
        ipv4_address: 172.20.0.11
    ports:
      - 2379:2379
      - 2380:2380
      - 2381:2381
      - 5432:5432
      - 6432:6432
      - 8008:8008
      - 8900:8900
      - 8901:8901
      - 8902:8902
    restart: unless-stopped

networks:
  otel-poc-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1