# [member]
ETCD_NAME=node1
ETCD_DATA_DIR="/var/lib/etcd/etcddata"
ETCD_WAL_DIR="/var/lib/etcd/etcdwal"
ETCD_SNAPSHOT_COUNT="10000"
ETCD_HEARTBEAT_INTERVAL="100"
ETCD_ELECTION_TIMEOUT="1000"
ETCD_LISTEN_PEER_URLS="http://172.20.0.11:2380"
ETCD_LISTEN_CLIENT_URLS="http://172.20.0.11:2379,http://127.0.0.1:2379"
ETCD_MAX_WALS="5"

#[cluster]
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://node1:2380"
ETCD_INITIAL_CLUSTER="node1=http://172.20.0.11:2380"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_ADVERTISE_CLIENT_URLS="http://node1:2379"
ETCD_STRICT_RECONFIG_CHECK="false"
ETCD_AUTO_COMPACTION_RETENTION="1"

#[security]
#ETCD_CERT_FILE="/var/lib/etcd/certs/etcd-server.pem"
#ETCD_KEY_FILE="/var/lib/etcd/certs/etcd-server-key.pem"
#ETCD_CLIENT_CERT_AUTH="false"
#ETCD_TRUSTED_CA_FILE="/var/lib/etcd/certs/ca.pem"
#ETCD_AUTO_TLS="false"
#ETCD_PEER_CERT_FILE="/var/lib/etcd/certs/etcd-server.pem"
#ETCD_PEER_KEY_FILE="/var/lib/etcd/certs/etcd-server-key.pem"
#ETCD_PEER_CLIENT_CERT_AUTH="true"
#ETCD_PEER_TRUSTED_CA_FILE="/var/lib/etcd/certs/ca.pem"
#ETCD_PEER_AUTO_TLS="false"
#ETCD_TLS_MIN_VERSION="TLS1.3"
#ETCD_TLS_MAX_VERSION="TLS1.3"

#[Auth]
#ETCD_AUTH_TOKEN="jwt,pub-key=/var/lib/etcd/certs/jwt_RS256.pub,priv-key=/var/lib/etcd/certs/jwt_RS256,sign-method=RS256"
#ETCD_BCRYPT_COST="10"
#ETCD_AUTH_TOKEN_TTL="300"

#[Profiling and monitoring]
ETCD_METRICS="basic"
ETCD_LISTEN_METRICS_URLS="http://0.0.0.0:2381"

#[logging]
ETCD_LOGGER="zap"
ETCD_LOG_OUTPUTS="/var/log/etcd/etcd.log"
ETCD_LOG_LEVEL="info"
ETCD_LOG_FORMAT="json"
ETCD_ENABLE_LOG_ROTATION="true"
ETCD_LOG_ROTATION_CONFIG_JSON='{"maxsize": 100, "maxage": 1, "maxbackups": 7, "localtime": true, "compress": true}'
