OTELCOL_OPTIONS="--config=/etc/otelcol-contrib/otelcol-config.yaml \
                 --config=/etc/otelcol-contrib/otelcol-custom.yaml \
                 --config=/etc/otelcol-contrib/otelcol-etcd.yaml \
                 --config=/etc/otelcol-contrib/otelcol-patroni.yaml \
                 --config=/etc/otelcol-contrib/otelcol-pgbackrest.yaml \
                 --config=/etc/otelcol-contrib/otelcol-pgbouncer.yaml \
                 --config=/etc/otelcol-contrib/otelcol-postgresql.yaml"